version: '3.4'

services:
  catalogdb:  
    image: mongo

  BasketDb:
    image: redis
  
  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4 

  Portainer:
    image: portainer/portainer-ce
  
  OrderDb:
    image: mcr.microsoft.com/mssql/server:2022-latest

      
  SpaceFork.eShop.Catalog.API:
    image: ${DOCKER_REGISTRY-}spacefork_eshop_catalog_api
    build:
      context: .
      dockerfile: Services/Catalog/SpaceFork.Services.Catalog.API/Dockerfile

  SpaceFork.eShop.Basket.API:
    image: ${DOCKER_REGISTRY-}spacefork_eshop_basket_api
    build:
      context: .
      dockerfile: Services/Basket/SpaceFork.eShop.Basket.API/Dockerfile
  
  spacefork.eshop.discount.api:
    image: ${DOCKER_REGISTRY-}spacefork_eshop_discount_api
    build:
      context: .
      dockerfile: Services/Discount/SpaceFork.eShop.Discount.API/Dockerfile

  spacefork.eshop.discount.grpc:
    image: ${DOCKER_REGISTRY-}spacefork_eshop_discount_grpc
    build:
      context: .
      dockerfile: Services/Discount/SpaceFork.eShop.Discount.gRPC/Dockerfile

  spacefork.eshop.ordering.api:
    image: ${DOCKER_REGISTRY-}spacefork_eshop_ordering_api
    build:
      context: .
      dockerfile: Services/Ordering/SpaceFork.eShop.Ordering.API/Dockerfile

volumes:
  portainer_data:
  catalog_data_mongo:
  postgres_data:
  pgadmindata:



