version: '3.4'

services:

  catalogdb:
    container_name: catalog-db-mongo
    ports:
      - "27017:27017"
    volumes:
      - catalog_data_mongo:/data/db

  BasketDb:
    container_name: Baket-db-redis
    ports:
      - "6379:6379"
    restart: always

  discountdb:
    container_name: discount_db_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=mhmad.abdelwahab@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmindata:/root/.pgadmin

  Portainer:
    restart: always
    container_name: portainer
    ports:
      - "8003:8000"
      - "8004:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - portainer_data:/data 

  OrderDb:
    container_name: order_db_sqlserver
    environment:
       ACCEPT_EULA: "Y"
       MSSQL_SA_PASSWORD: "Mm2161181**##@@"
       MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    restart: always
####################################################################################################


  SpaceFork.eShop.Catalog.API:
    container_name: SpaceFork_eShop_Catalog_API
    depends_on: 
      - catalogdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DatabaseSettings:ConnectionString=mongodb://catalog-db-mongo:27017
      - DatabaseSettings:DatabaseName=Catalogdb
      - DatabaseSettings:CollectionName=Products
    ports:
      - "8000:80"
    restart: always 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    


  SpaceFork.eShop.Basket.API:
    
    container_name: SpaceFork_eShop_Basket_API
    
    depends_on: 
      - SpaceFork.eShop.Catalog.API
      - BasketDb
    
    ports:
      - "7000:80"
    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Redis:ConnectionString=BasketDb:6379
      - GrpcSettings:DiscountUrl=http://SpaceFork_eShop_Discount_gRPC
    restart: always


  spacefork.eshop.discount.api:
    container_name: SpaceFork_eShop_Discount_API
    depends_on:
      - discountdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - PostgresDbSettings:ConnectionString=Server=discount_db_postgres;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    restart: always

  spacefork.eshop.discount.grpc:
    container_name: SpaceFork_eShop_Discount_gRPC
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PostgresDbSettings:ConnectionString=Server=discount_db_postgres;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;
    restart: always
    ports:
      - "5001:80"
    

  spacefork.eshop.ordering.api:
    container_name: SpaceFork_eShop_Ordering_API
    restart: always
    environment:
      - ConnectionStrings:Default=server=OrderDb;Database=OrderDb;User Id = sa;Password=Mm2161181**##@@;Encrypt=True;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "4001:80"

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
