version: '3.4'

services:
  catalogdb:  
    image: mongo

  BasketDb:
    image: redis
  
  Portainer:
    image: portainer/portainer-ce

      
  SpaceFork.eShop.Catalog.API:
    image: ${DOCKER_REGISTRY-}spaceforkeshopcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/SpaceFork.Services.Catalog.API/Dockerfile

  SpaceFork.eShop.Basket.API:
    image: ${DOCKER_REGISTRY-}spacefork_eshop_basket_api
    build:
      context: .
      dockerfile: Services/Basket/SpaceFork.eShop.Basket.API/Dockerfile
  
